--- 
clone: 
  depth: 1
kind: pipeline
name: Blaster4385Pipeline
steps: 
  - name: submodules
    image: alpine/git
    commands:
  - 
    environment: 
      TG_TOKEN: 
        from_secret: TOKEN
      CHANNEL_ID:
        from_secret: CHATID
    commands:
      - "apt-get update"
      - "apt-get -y install curl"
      - "curl https://raw.githubusercontent.com/Blaster4385/scripts/main/build_aosp | bash"
    image: ubuntu:latest
    name: Build
    trigger: 
      branch: 
        - master
