--- 
clone: 
  depth: 1
kind: pipeline
name: Blaster4385Pipeline
steps: 
  - 
    environment:
      TZ: Asia/Dubai
      TG_TOKEN: 
        from_secret: TOKEN
      CHANNEL_ID:
        from_secret: CHATID
    commands:
      - "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone"
      - "apt update"
      - "apt -y install curl wget"
      - "apt -y install git"
      - "apt -y install python-minimal
      - "apt -y install repo
      - "curl https://raw.githubusercontent.com/Blaster4385/scripts/main/setup.sh | bash"
      - "curl https://raw.githubusercontent.com/Blaster4385/scripts/main/build_aosp | bash"
    image: ubuntu:latest
    name: Build
    trigger: 
      branch: 
        - master
